-- ============================================================
-- COD CRM — Migration: Super Admin Support
-- ============================================================
-- Adds super_admin role to users table
-- Creates super_admins table for platform-level admins (no store_id)
-- ============================================================

SET NAMES utf8mb4;

-- 1. Create super_admins table (platform-level, no store_id)
CREATE TABLE IF NOT EXISTS `super_admins` (
    `id`          INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `name`        VARCHAR(100) NOT NULL,
    `email`       VARCHAR(255) NOT NULL UNIQUE,
    `password`    VARCHAR(255) NOT NULL,
    `role`        VARCHAR(20) NOT NULL DEFAULT 'super_admin',
    `status`      ENUM('active', 'inactive') DEFAULT 'active',
    `last_login`  DATETIME DEFAULT NULL,
    `created_at`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at`  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `idx_super_admins_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Seed default super admin (password: Admin@123456)
-- Password hash: $2y$12$ generated by PHP password_hash()
-- IMPORTANT: Change this password immediately after first login!
INSERT INTO `super_admins` (`name`, `email`, `password`, `role`) VALUES
('Super Admin', 'admin@codcrm.com', '$2y$12$LJ3m4ys6Gx3CYg2Z7RqHPOQYJGkVFYHV1UHqJZFvWLyrxSAkCjKi6', 'super_admin')
ON DUPLICATE KEY UPDATE `name` = VALUES(`name`);
